[workspace]
channels = ["conda-forge"]
name = "CTF"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
pwntools = ">=4.15.0,<5"
ipython = ">=9.17.1,<10"
six = ">=1.17.0,<2"
